// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0kdQssho5UoLO6j40mXhJy89utOBRhk',
    appId: '1:622328327723:web:f8253e804802a71cffc46e',
    messagingSenderId: '622328327723',
    projectId: 'foresight-5c783',
    authDomain: 'foresight-5c783.firebaseapp.com',
    storageBucket: 'foresight-5c783.appspot.com',
    measurementId: 'G-QGVLNDZ3KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARzIZzhQJSOUn8D35LcXpKkmD5Q6W3RJg',
    appId: '1:622328327723:android:6e4cb0e553dc310dffc46e',
    messagingSenderId: '622328327723',
    projectId: 'foresight-5c783',
    storageBucket: 'foresight-5c783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2DQdtAEVqMrHdy1EsY_uQFctldlx_ljw',
    appId: '1:622328327723:ios:971bd2b158ed159bffc46e',
    messagingSenderId: '622328327723',
    projectId: 'foresight-5c783',
    storageBucket: 'foresight-5c783.appspot.com',
    iosBundleId: 'com.example.foresightNewsAndArticles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2DQdtAEVqMrHdy1EsY_uQFctldlx_ljw',
    appId: '1:622328327723:ios:971bd2b158ed159bffc46e',
    messagingSenderId: '622328327723',
    projectId: 'foresight-5c783',
    storageBucket: 'foresight-5c783.appspot.com',
    iosBundleId: 'com.example.foresightNewsAndArticles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt0kdQssho5UoLO6j40mXhJy89utOBRhk',
    appId: '1:622328327723:web:7941b9eb1c7f0667ffc46e',
    messagingSenderId: '622328327723',
    projectId: 'foresight-5c783',
    authDomain: 'foresight-5c783.firebaseapp.com',
    storageBucket: 'foresight-5c783.appspot.com',
    measurementId: 'G-S2631G45WQ',
  );
}
